name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0  # Fetch full history to ensure we have latest
      
      - name: Install Zola
        run: |
          wget -q -O zola.tar.gz https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola.tar.gz
          sudo mv zola /usr/local/bin/
          zola --version
      
      - name: Build site
        run: |
          echo "Building site..."
          zola build --output-dir public
          echo "Build complete"
      
      - name: Verify build
        run: |
          echo "=== Verification ==="
          echo "Checking HTML for data-theme attribute:"
          if grep -q 'data-theme="toggle"' public/index.html; then
            echo "✓ data-theme attribute found"
          else
            echo "✗ WARNING: data-theme not found"
            echo "HTML tag:"
            grep -o '<html[^>]*>' public/index.html || echo "No HTML tag found"
          fi
          
          echo ""
          echo "Checking if toggle-theme.js exists:"
          if [ -f public/js/toggle-theme.js ]; then
            echo "✓ toggle-theme.js found"
            echo "First few lines:"
            head -5 public/js/toggle-theme.js
          else
            echo "✗ toggle-theme.js missing"
            echo "Files in public/js/:"
            ls -la public/js/ || echo "public/js/ directory doesn't exist"
          fi
          
          echo ""
          echo "Verifying init-theme.js content:"
          if grep -q "dataset.theme" public/js/init-theme.js; then
            echo "✓ init-theme.js uses dataset.theme"
            echo "Relevant line:"
            grep "dataset.theme" public/js/init-theme.js | head -1
          else
            echo "✗ init-theme.js has wrong content"
            echo "Content:"
            head -15 public/js/init-theme.js
          fi
          
          echo ""
          echo "Checking if toggle-theme.js is loaded in HTML:"
          if grep -q "toggle-theme.js" public/index.html; then
            echo "✓ toggle-theme.js is loaded"
          else
            echo "✗ toggle-theme.js not found in HTML"
          fi
      
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: noos.blog
      
      - name: Trigger GitHub Pages rebuild
        run: |
          echo "Triggering GitHub Pages rebuild to clear CDN cache..."
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/pages/builds || echo "Rebuild trigger attempted (may not be available for all repos)"

