name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0  # Fetch full history to ensure we have latest
      
      - name: Install Zola
        run: |
          wget -q -O zola.tar.gz https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf zola.tar.gz
          sudo mv zola /usr/local/bin/
          zola --version
      
      - name: Build site
        run: |
          echo "Building site..."
          zola build --output-dir public
          echo "Build complete"
          echo ""
          echo "Verifying critical files:"
          ls -la public/posts/ 2>/dev/null | head -10 || echo "posts directory not found"
          if [ -f "public/posts/github-actions-when-automation-meets-reality/index.html" ]; then
            echo "✓ GitHub Actions blog post exists"
          else
            echo "✗ GitHub Actions blog post NOT found!"
            exit 1
          fi
      
      - name: Verify build
        run: |
          echo "=== Verification ==="
          echo "Checking HTML for data-theme attribute:"
          if grep -q 'data-theme="toggle"' public/index.html; then
            echo "✓ data-theme attribute found"
          else
            echo "✗ WARNING: data-theme not found"
            echo "HTML tag:"
            grep -o '<html[^>]*>' public/index.html || echo "No HTML tag found"
          fi
          
          echo ""
          echo "Checking if toggle-theme.js exists:"
          if [ -f public/js/toggle-theme.js ]; then
            echo "✓ toggle-theme.js found"
            echo "First few lines:"
            head -5 public/js/toggle-theme.js
          else
            echo "✗ toggle-theme.js missing"
            echo "Files in public/js/:"
            ls -la public/js/ || echo "public/js/ directory doesn't exist"
          fi
          
          echo ""
          echo "Verifying init-theme.js content:"
          if grep -q "dataset.theme" public/js/init-theme.js; then
            echo "✓ init-theme.js uses dataset.theme"
            echo "Relevant line:"
            grep "dataset.theme" public/js/init-theme.js | head -1
          else
            echo "✗ init-theme.js has wrong content"
            echo "Content:"
            head -15 public/js/init-theme.js
          fi
          
          echo ""
          echo "Checking if toggle-theme.js is loaded in HTML:"
          if grep -q "toggle-theme.js" public/index.html; then
            echo "✓ toggle-theme.js is loaded"
          else
            echo "✗ toggle-theme.js not found in HTML"
          fi
          
          echo ""
          echo "=== Blog Post Verification ==="
          BLOG_POST="public/posts/github-actions-when-automation-meets-reality/index.html"
          if [ -f "$BLOG_POST" ]; then
            echo "✓ Blog post file exists"
            if grep -q "Template Conflicts and Browser Caching" "$BLOG_POST"; then
              echo "✓ 'Template Conflicts and Browser Caching' found in blog post"
            else
              echo "✗ WARNING: 'Template Conflicts and Browser Caching' NOT found in blog post"
              echo "Checking for Issue #5:"
              grep -i "issue.*5\|template\|browser.*cache" "$BLOG_POST" | head -3 || echo "No matches found"
            fi
            if grep -q "Issue #5" "$BLOG_POST"; then
              echo "✓ 'Issue #5' found in blog post"
            else
              echo "✗ WARNING: 'Issue #5' NOT found in blog post"
            fi
            echo ""
            echo "Blog post line count:"
            wc -l "$BLOG_POST"
          else
            echo "✗ Blog post file NOT found at $BLOG_POST"
            echo "Available blog posts:"
            ls -la public/posts/ 2>/dev/null || echo "public/posts/ directory doesn't exist"
          fi
          
          echo ""
          echo "=== Build Summary ==="
          echo "Total pages built:"
          find public -name "index.html" -type f | wc -l
          echo "Total blog posts:"
          find public/posts -name "index.html" -type f 2>/dev/null | wc -l
      
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: noos.blog
      
      - name: Post-deployment verification
        run: |
          echo "=== Deployment Complete ==="
          echo "Waiting 10 seconds for GitHub Pages to update..."
          sleep 10
          echo ""
          echo "Note: It may take a few minutes for GitHub Pages to rebuild and serve the new content."
          echo "Check the Actions tab and GitHub Pages settings to verify deployment status."

